on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nhartland/love-build@master
        id: love-build
        with:
          app_name: "egg_throw"
          love_version: "11.5"
      - uses: softprops/action-gh-release@v2
        with:
          files:
            - ${{ steps.love-build.outputs.macos-filename }}
            - ${{ steps.love-build.outputs.win32-filename }}
            - ${{ steps.love-build.outputs.win64-filename }}
            - ${{ steps.love-build.outputs.love-filename }}
